version: "3"

services:
  web:
      build: ./config/dockerfiles/nginx
      image: nginx
      volumes:
          - ./../website:/var/www/vhosts/website
          - ./config/site.conf:/etc/nginx/conf.d/site.conf
          - ./nginx/log:/var/log/nginx
      links:
          - php
      container_name: web
      expose:
         - 80
      environment:
         VIRTUAL_HOST: ${VIRTUAL_HOST}
      restart: on-failure:10

  php:
      build: ./config/dockerfiles/php/dev
      image: dev-php:7.2-fpm
      volumes:
          - ./../website:/var/www/vhosts/website
          - ./profiler:/tmp/xdebug
          - /etc/localtime:/etc/localtime
      container_name: php
      extra_hosts:
          - "${VIRTUAL_HOST}:${NGINX_PROXY_IP}"
      environment:
          XDEBUG_CONFIG: remote_host=${NGINX_PROXY_IP}
      working_dir: /var/www/vhosts/website/
      restart: on-failure:10

  nginx-proxy:
      image: jwilder/nginx-proxy
      container_name: nginx-proxy
      ports:
        - "80:80"
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  default:
    external:
      name: nginx-proxy